### ISSUE TITLE
Sequentially running selected sentences and immediately stopping when any sentence has failed

### ISSUE THREAD

**Issue by aqjune** [monadius/vscode-hol-light#10]
Hi,

Does VSCode terminal provide a mechanism to check whether running the latest sentence failed or not?
Checking 'failed or not' can be at the moment done by heuristically matching 'Error:' at the beginning of any of output lines. Actually, in the case of s2n-bignum, this is more relaxed by simply grepping 'error' or 'exception' words from the output: https://github.com/awslabs/s2n-bignum/blob/main/tools/run-proof.sh#L33
However, does VSCode terminal support getting the standard output of the running process in terminal? When I was playing with OCaml's vscode plugin, I could not find such functionality.

I was wondering because I thought it would be great if vscode-hol-light could support sequentially running selected sentences and immediately stopping when any sentence has failed.
For example, assume that a user has selected this two sentences and sent it to REPL:
```
let x = 3 + "a";;
let y = x + x;;
```
Since the RHS of `x` is bogus, the first sentence will fail. In the current version of plugin,  the second sentence is executed anyway, but if it stops immediately with some mark at first sentence there (or highlighting the first sentence differently?) a user can identify that the first sentence `let x = ..` was problematic.

Thanks,

**Comment by monadius** [comment]
It is possible to create a separate process for the OCaml (HOL Light) REPL which is connected to a VSCode pseudoterminal (this approach is used in the HOL4 VSCode extension). Then it will be possible to read stdout and stderr streams of the REPL and react to potential errors. But there is no easy and robust approach to recognize when the execution of a command is done by the REPL (either normally or with a failure). The OCaml REPL emits `#` after the command execution is done. But a command itself may print this character. Maybe it is not a serious issue. I will experiment with the separate process approach and see how well it will work for executing a sequence of commands with potential errors.

**Comment by aqjune** [comment]
I looked for a solution by myself and this indeed seems to be hard unless the toplevel implementation itself is modified to notify that evaluation is finished to the user.
I think an ad-hoc workaround is to simply insert, say, `print_endline "magic string";;` after each statement and recognize the printed magic string as a separator.
What do you think about using a pseudoterminal and omitting printing the magic string thingy in the pane visible to the user?

**Comment by aqjune** [comment]
BTW, your repo is now appearing at https://hol-light.github.io/ FYI. :)

**Comment by monadius** [comment]
It is a good idea to print some magical value after each statement. It should work for almost all cases. Unfortunately, it is not possible to detect errors in this way. But error messages can be identified with `Error: ...` or `Exception: ...`.

Alternatively, it could be possible to execute all statements with `Toploop.execute_phrase` and `Toploop.parse_toplevel_phrase` functions. In this way, it should be possible to catch all exceptions.

**Comment by monadius** [comment]
> BTW, your repo is now appearing at https://hol-light.github.io/ FYI. :)

I am glad to hear that. Could you also add a direct link to the Marketplace: https://marketplace.visualstudio.com/items?itemName=monadius.hol-light-simple

**Comment by aqjune** [comment]
Hi @monadius,

I have been working on writing more proofs using the latest version of this plugin for a while. The go-to definition is working flawlessly! :)

Regarding the context of this issue, I remember that our last conversation was to use an approach similar to https://github.com/aqjune/toplevel-light, but more portable in the sense that its toplevel_light.ml is simply run after the REPL is launched.
I think your approach makes sense to me. Always thank your effort & let me know if you need some help!

p.s: Abdal (@abdoo8080 , I hope I found him correctly..! Hi Abdal! :D ) just also started using the plugin. :) I just wanted to introduce him.

**Comment by monadius** [comment]
Hi @aqjune 

It is good to hear that everything works without any major issues and that new people are starting to use the extension (Hi Abdal!). 

I am busy right now but I am going to resume my work on the extension soon. In particular, I am going to implement a pseudo terminal for the HOL Light REPL and modify the toplevel output based on the ideas from your project. It will be also possible to implement additional features by modifying the toplevel output. For example, I am thinking about special queries which can return some useful information about loaded definitions. Right now, the extension does not display any type information (unless it is explicitly given in a definition) but it may be possible to get the type information from the toplevel directly with some special commands.

**Comment by aqjune** [comment]
The pseudoterminal idea sounds exciting and I am eager to try its prototype! :)

> For example, I am thinking about special queries which can return some useful information about loaded definitions. Right now, the extension does not display any type information (unless it is explicitly given in a definition) but it may be possible to get the type information from the toplevel directly with some special commands.

I think [`print_types_of_subterms`](https://github.com/jrh13/hol-light/blob/master/Help/print_types_of_subterms.hlp) might be helpful in this case. This option has been recently added and can have three integral values (0~2).

**Comment by abdoo8080** [comment]
Hi @monadius,

I'm an intern at AWS, currently working on constant time proofs for s2n-bignum. I recently started learning HOL Light for the project. Your VS Code extension has been invaluable in this process, especially with features like hover information, auto-completion, and go-to-definition. I hope you don’t mind if I request some additional features for the extension in the future!

> it may be possible to get the type information from the toplevel

That would be super helpful!

**Comment by monadius** [comment]
Hi @abdoo8080! Feel free to request any new features or open issues if you find bugs or problems with the extension.

**Comment by monadius** [comment]
After several experiments, I implemented a client-server model for executing HOL Light commands and returning execution results. There are two ways to start a server. The simplest way is to use a new command (`HOL Light: Start Server`) to start a server directly inside an existing REPL and to connect to this server. It is also possible to start a server by clicking the status bar item `Start Server` (which appears whenever a regular HOL Light REPL is open): 

![Screenshot from 2024-08-22 17-19-26](https://github.com/user-attachments/assets/553d79dd-4a1d-49bd-a3d5-0141b58aaad9)

It is important to make sure that the REPL is not executing any commands before starting a new server instance.

A server can be also started manually inside a HOL Light REPL (any REPL, not necessarily running inside VS Code). The server code can be obtained from https://github.com/monadius/hol_server/. After starting a server, it is enough to select "Connect to HOL Light server" in the list of HOL Light startup scripts.

Here are pros and cons of the Client-Server approach.

### Client-Server pros:

- It is the most reliable solution for executing HOL Light commands and getting results back. Other approaches which I tried (printing some special messages before and after each command or using a modified OCaml Toplevel) do not work well when inputs contain errors (especially when Camlp5 preprocessing is enabled). Moreover, it is difficult to parse results if everything is printed directly to stdout and stderr.

- It is easy to start a server inside a Docker container, a virtual machine, or on a remote machine. 

### Client-Server cons:

- It is a multi-step process to start a server and to connect to it (as described above). I tried to make this multi-step process as simple as possible with the command `HOL Light: Start Server`.

- Works with OCaml 4.14 only: `Toploop.use_input` is available starting from OCaml `4.14.0`. It is possible to evaluate expressions with other `Toploop` functions but there are issues with error messages. I don't think that it is a serious restrictions: OCaml 4.14.2 is the current LTS release.

- Currently, stdout (and stderr) output is displayed after executing a command. It is not possible to see any command progress until it is finished. I plan to update the server and make it possible to display stdout (and stderr) results as soon as they become available. It will be necessary to use OCaml threads. I tried to avoid threads because they do not work very well with signals (and it is required to support SIGINT in order to be able to interrupt long or infinite executions). But everything should be fine as long as the main thread executes all commands. (I tried to implement a multi-threaded server a long time ago but it was not possible to route SIGINT to a specific thread even with `Thread.sigmask`; maybe everything works better now.)

- In order to interrupt a command for a server running on a remote host or for a server inside a checkpointed REPL (DMTCP), it is necessary to type Ctrl+C directly in the corresponding server REPL window. The current client implementation sends the interrupt signal directly to the process which runs the server. This process is identified by `Unix.getpid ()`. But the PID of a checkpointed process is different from the result returned by this function. This issue could be solved by implementing a multi-threaded server.


The client-server model provides feedback to the extension. So now it is possible to get results of all commands and do something with these results. First of all, it is now possible to know whether a command completed successfully or not. I added different highlight colors for succesfully completed commands (light green) and for failed commands (light red). Also the current issue is addressed: Whenever multiple commands are executed, the execution stops after the first failure. It works when multiple commands are selected and executed with Alt+E or when a new command for executing all commands up to the cursor position (Alt+A) is used.

Another thing which I added is the ability to display information about global definitions which are not parsed by the extension. For instance, the `ARITH` theorem is not parsed (because it is not defined with `prove`) but now it is possible to display its definition in a hover message or in the autocompletion window.

I added two more features. It is now possible to open HOL Light files as interactive notebooks (https://code.visualstudio.com/blogs/2021/11/08/custom-notebooks). To open an .ml or .hl file as a notebook, right click on it and select "Open with..." and the select "HOL Light Notebook". Here is a HOL Light notebook example:

![Screenshot from 2024-08-22 17-37-05](https://github.com/user-attachments/assets/79214163-a3ad-431d-a6b1-9ccbe42d1079)

I think that interactive notebooks could be useful for HOL Light presentations or tutorials.

Another new feature is the ability to display search results (obtained via Alt+S) in a separate window. It looks like this:

![Screenshot from 2024-08-22 17-38-58](https://github.com/user-attachments/assets/83ffa5aa-8436-48af-b8d1-895d6efcc486)

I use a standard view from VS Code for which it is not possible to customize any text styles. I am not satisfied with the current Search Results view because it could be difficult to find required theorems in this list. So it should be considered as work in progress. I will try to improve the visual style of search results by implementing a custom view.

I would appreciate if you test this new Client-Server execution model before I publish it. You can either download and install the compiled extension (https://github.com/monadius/vscode-hol-light/releases/tag/2.1.0-rc) or you can compile it yourself by checking out the branch `treeview`.

I would also like to get your ideas about other features which can be implemented with the Client-Server model.

**Comment by aqjune** [comment]
Hi @monadius , there are lots of amazing features. Thanks for your hard work; I will thoroughly test the new features soon when busy stuffs on my side are finished in a day or two.

> Currently, stdout (and stderr) output is displayed after executing a command. It is not possible to see any command progress until it is finished. I plan to update the server and make it possible to display stdout (and stderr) results as soon as they become available.

This seems to be a feature that I might want when proving s2n-bignum stuffs. It has a symbolic simulation tactic for an assembly program, and it prints to stdout how many instructions have been simulated so far with many useful informations. Would it be possible to have a separate debug-like window in vscode and the stdout/stderr from the REPL are simply redirected to the window?

**Comment by monadius** [comment]
I think that I will be able to implement stdout (stderr) redirection with real time updates on the client side pretty soon. But there is always an option to not redirect stdout and just print stdout results in a terminal window which runs the server process.

**Comment by aqjune** [comment]
Aha, makes sense! That would be a very straightforward solution. :)

**Comment by monadius** [comment]
I implemented a new server which can send stdout/stderr results in real time. It is also possible to interrupt this new server running inside a checkpointed REPL or on a remote machine with ALT+C.

The new extension version can be downloaded at https://github.com/monadius/vscode-hol-light/releases/tag/2.1.1-rc

I deleted the branch `treeview`. To get the most recent source code version, checkout the branch `terminal`.

**Comment by aqjune** [comment]
Hi, sorry for delay. I tested your 2.1.1-rc using my dmtcp-checkpointed HOL Light image and it worked great. :)
I have one question - The Execute Current Tactic feature can pick one tactic before THEN, but to control the granularity I typically manually select a few statements by myself and run Execute Current Tactic. It seems the green-color highlighting does not work well in this case, however.
Could you check whether this is reproduced in your case as well, please? Thanks.

**Comment by monadius** [comment]
I fixed this tactic highlighting bug in the latest commit.

**Comment by monadius** [comment]
I published the new extension version.
