### ISSUE TITLE
`;;` in a string causes wrong selection of a sentence

### ISSUE THREAD

**Issue by aqjune** [monadius/vscode-hol-light#3]
How to reproduce:

Given a text, say,

```
let x = ";;" in x;;
```

If I put a cursor at the beginning of the line and run 'Execute Current Tactic', only `let x = "` segment is selected and evaluated.

Would be great if this is fixed..! :)
Not an urgent issue, so please feel free to take your time.

**Comment by monadius** [comment]
Fixed in a new [release](https://github.com/monadius/vscode-hol-light/releases/tag/0.3.0). The new statement selection algorithm scans the whole file and correctly skips comments and string literals. I tested the new algorithm on the largest HOL Light files (e.g., `topology.ml`) and did not notice any performance issues. Just in case, I added a configuration option to use a simple less accurate algorithm ("Hol-light: Simple Selection") if the new algorithm is too slow for some reason.

**Comment by aqjune** [comment]
Thanks a lot for your work! It works great.
