### ISSUE TITLE
Autocompletion of keywords in `Help/*`?

### ISSUE THREAD

**Issue by aqjune** [monadius/vscode-hol-light#6]
The tactics/functions/variables listed in `Help/*` are used universally in any HOL Light proofs and also provided by HOL Light kernel without further library loads.

It would be great if they are provided as autocompletion because this can remind programmers existence of useful items.

This isn't an urgent feature and I rather wanted to share my thought about this.

**Comment by monadius** [comment]
I published a new version (1.1.0) of the extension where autocompletion works for items defined in the HOL Light `Help` directory. Hover messages are also displayed for these items. In order to enable this feature, it is necessary to set a HOL Light path in the extension. It could be done by editing the `hol-light.path` configuration setting or by invoking the `HOL Light: Set HOL Light Path` command from the command palette (it opens a directory selection dialog).

**Comment by aqjune** [comment]
Thanks a lot! It is wonderful. :)
